# Site settings
title: Claudio Tomasi
baseurl: ""
url: "https://claudiotomasi.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Claudio Tomasi
  desc: Hello nice to meet you
  email: claudio.tomasi@unibg.it
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: claudiotomasi
  orcid: 0009-0009-6501-2671
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/claudiotomasi/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate-v2

# Permalinks
# permalink: /:year-:month-:day/:title
# permalink: /:categories/:year/:title

pagination:
  enabled: false
  per_page: 5
  permalink: /portfolio/page/:num
  category: portfolio

collections:
  portfolio:
    output: true  # Ensures that these posts are included in the site


paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
